version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_DB=restdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=qwerty123
    restart: unless-stopped
    ports:
      - "54320:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data

  # app:
  #   image: app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: /usr/local/bin/app
  #   ports:
  #     - "80:8080"
  #   environment:
  #     DB_HOST: psql
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   links:
  #     - db